config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'toppages#index'

  get "signup", to: "users#new"
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  post 'guest_login', to: "guest_sessions#create"

  resources :users, only: %i[show create edit update] do
    member do
      get :followings
      get :followers
      get :favorites
      get :bookcases
      get :draft
    end
  end
  resources :favorites, only: %i[create destroy]
  resources :relationships, only: %i[create destroy]
  resources :bookcases, only: %i[create destroy]

  get 'books/search', to: "books#search"
  resources :books, only: %i[show] do
    resources :reviews, only: %i[show create update destroy] do
      resources :comments, only: %i[create update edit destroy]
    end
    collection do
      get "reviews", to: "reviews#index"
    end
  end

  resources :notifications, only: %i[index]
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :review
  has_many :notifications, dependent: :destroy

  validates :content, presence: true, length: { maximum: 255 }
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  before_action :require_login
  before_action :set_comment, only: %i[update edit destroy comment_correct_user]
  before_action :set_review
  before_action :set_comments, only: %i[create edit destroy]
  before_action :comment_correct_user, only: %i[update edit destory]

  def create
    @comment = current_user.comments.build(comment_params)
    if @comment.save
      @review.create_notification_comment(current_user, @comment.id)
    else
      render "post/show"
      flash[:alert] = "コメントを(140文字以内で)入力してください"
    end
  end

  def update
    if @comment.update(comment_params)
      redirect_to book_review_path(@review.book, @review)
    else
      redirect_back(fallback_location: root_path)
      flash[:alert] = "コメントを(140文字以内で)入力してください"
    end
  end

  def edit
    @book = @review.book
    render "reviews/show"
  end

  def destroy
    @comment.destroy
  end

  private

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def set_review
    @review = Review.find(params[:review_id])
  end

  def set_comments
    @comments = @review.comments.order(id: :desc)
  end

  def comment_params
    params.require(:comment).permit(:content, :review_id)
  end

  def comment_correct_user
    redirect_to root_url unless @comment.user_id == current_user.id
  end
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class="row comment-boxs">
  <div class="col-md-6 comment_area">
    <%= render "comments/comment_area" %>
  </div>
  <div class="col-md-6">
    <%= form_with(model:[@review.book, @review, @comment]) do |f|%>
      <%= f.text_area :content, class:"form-control mb-2", rows: 3 %>
      <%= f.hidden_field :review_id, value: @review.id %>
      <%= f.submit 'コメントする', class: 'submit-btn txt-xxs' %>
    <% end %>
  </div>
</div>

app/views/comments/_comment_area.html.erb
<% if @comments.exists? %>
  <% @comments.each do |comment| %>
    <div class="comment-box mb-3">
      <div class="flex-between">
        <div class="comment-user flex">
          <!-- ユーザーの画像 -->
          <div>
            <% if comment.user.user_image? %>
              <%= link_to (image_tag comment.user.user_image.url, class: "user-image"), user_path(comment.user.id) %>
            <% else %>
              <%= link_to (image_tag "user_default", class: "user-image"), user_path(comment.user.id) %>
            <% end %>      
          </div>
          <!-- ユーザー名 -->
          <div class="comment-user-name pl-2">
            <%= link_to comment.user.name, user_path(comment.user), class: "txt-xs thin-font" %>
          </div>
        </div>
        <div class="edit-delete">
          <% if current_user == comment.user %>
            <%= link_to edit_book_review_comment_path(comment.review.book, comment.review, comment) do %>
              <i class="far fa-edit fa-lg m-1"></i>
            <% end %>
            <%= link_to [comment.review.book, comment.review, comment], method: :delete, remote: true do  %>
              <i class="fas fa-trash fa-lg m-1"></i>
            <% end %>
          <% end %>  
        </div>
      </div>
      <!-- コメント -->
      <div class="comment">
        <%= simple_format(comment.content, class: "thin-font pt-2 txt-xxs") %>    
      </div>
    </div>
  <% end %>
<% else %>
  <p class="mt-2">コメントはまだありません</p>
<% end %>

app/views/comments/create.js.erb
$("textarea").val("")
$(".comment_area").html("<%= j(render "comments/comment_area") %>");

app/views/comments/destroy.js.erb
$(".comment_area").html("<%= j(render "comments/comment_area") %>");