config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'toppages#index'

  get "signup", to: "users#new"
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  post 'guest_login', to: "guest_sessions#create"

  resources :users, only: %i[show create edit update] do
    member do
      get :followings
      get :followers
      get :favorites
      get :bookcases
      get :draft
    end
  end
  resources :favorites, only: %i[create destroy]
  resources :relationships, only: %i[create destroy]
  resources :bookcases, only: %i[create destroy]

  get 'books/search', to: "books#search"
  resources :books, only: %i[show] do
    resources :reviews, only: %i[show create update destroy] do
      resources :comments, only: %i[create update edit destroy]
    end
    collection do
      get "reviews", to: "reviews#index"
    end
  end

  resources :notifications, only: %i[index]
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 20 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  enum gender: { "男性": 1, "女性": 2 }
  mount_uploader :user_image, UserImageUploader

  has_many :reviews, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_many :relationships, dependent: :destroy
  has_many :followings, through: :relationships, source: :follow

  has_many :reverses_relationship, class_name: 'Relationship', foreign_key: 'follow_id', dependent: :destroy
  has_many :followers, through: :reverses_relationship, source: :user

  has_many :favorites, dependent: :destroy
  has_many :favorings, through: :favorites, source: :review

  has_many :bookcases, dependent: :destroy
  has_many :register_books, through: :bookcases, source: :book

  has_many :active_notifications, class_name: "Notification", foreign_key: "visitor_id", dependent: :destroy
  has_many :passive_notifications, class_name: "Notification", foreign_key: "visited_id", dependent: :destroy

  def feed_reviews
    Review.where(user_id: following_ids + [id]).includes(:user, :book)
  end

  def follow(other_user)
    relationships.find_or_create_by(follow_id: other_user.id) unless self == other_user
  end

  def unfollow(other_user)
    relationship = relationships.find_by(follow_id: other_user.id)
    relationship&.destroy
  end

  def following?(other_user)
    followings.include?(other_user)
  end

  def favor(other_review)
    favorites.find_or_create_by(review_id: other_review.id)
  end

  def unfavor(other_review)
    favorite = favorites.find_by(review_id: other_review.id)
    favorite&.destroy
  end

  def favoring?(other_review)
    favorings.include?(other_review)
  end

  def register(other_book)
    bookcases.find_or_create_by(book_id: other_book.isbn)
  end

  def unregister(other_book)
    bookcase = bookcases.find_by(book_id: other_book.isbn)
    bookcase&.destroy
  end

  def register?(other_book)
    register_books.include?(other_book)
  end

  def create_notification_follow(current_user)
    temp = Notification.where(["visitor_id = ? and visited_id = ? and action = ?", current_user.id, id, "follow"])
    return unless temp.blank?

    notification = current_user.active_notifications.new(
      visited_id: id,
      action: "follow"
    )
    notification.save if notification.valid?
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :require_login, only: %i[show edit update followings followers favorites bookcases draft]
  before_action :set_user, only: %i[show edit update followings followers favorites bookcases draft self_user]
  before_action :self_user, only: %i[edit update draft]

  def show
    @reviews =
      if current_user == @user
        @user.feed_reviews.where(status: 1).order(updated_at: :desc).page(params[:page]).per(6)
      else
        @user.reviews.where(status: 1).includes(:user, :book).order(updated_at: :desc).page(params[:page]).per(6)
      end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_url
      flash[:success] = "ユーザー登録完了しました。"
      session[:user_id] = @user.id
    else
      render :new
      flash.now[:danger] = "ユーザー登録ができませんでした。"
    end
  end

  def edit; end

  def update
    if @user.update(profile_params)
      flash[:success] = 'プロフィールを更新しました。'
      redirect_to @user
    else
      render :edit
      flash.now[:danger] = 'プロフィーを更新できませんでした。'
    end
  end

  def followings
    @followings = @user.followings.order(id: :desc).page(params[:page]).per(9)
  end

  def followers
    @followers = @user.followers.order(id: :desc).page(params[:page]).per(9)
  end

  def favorites
    @favorites = @user.favorings.order(updated_at: :desc).page(params[:page]).per(6)
  end

  def bookcases
    @bookcases = @user.register_books.order(updated_at: :desc).page(params[:page]).per(10)
  end

  def draft
    @draft_reviews = @user.reviews.where(status: 0).includes(:user, :book).order(updated_at: :desc).page(params[:page]).per(10)
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def self_user
    redirect_to root_url unless @user == current_user
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def profile_params
    params.require(:user).permit(:name, :gender, :user_image, :birthday, :introduction)
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
  def user_age
    if @user.birthday
      user_birthday = @user.birthday.strftime("%Y%m%d").to_i
      today = Date.today.strftime("%Y%m%d").to_i
      @age ||= (today - user_birthday) / 10_000.round
    else
      @age = "-"
    end
  end
end

app/views/users/_follow_user.html.erb
<div class="container mt-5 mb-5">
  <div class="offset-md-1 col-md-10">
    <% users.each do |user| %>
      <div class="follow-user flex mt-2">
        <div>
          <% if user.user_image? %>
            <%= link_to (image_tag user.user_image.url, class: "user-image-l"), user_path(user) %>
          <% else %>
            <%= link_to (image_tag "user_default.png", class: "user-image-l"), user_path(user) %>
          <% end %>
        </div>
        <div class="pl-2 follow-user-content">
          <div class="follow-user-name">
            <%= link_to user.name, user_path(user), class: "txt-xs mb-1" %>
            <div id="follow_buttons_<%= user.id %>"><%= render "relationships/follow_button", user: user %></div>
          </div>
          <div class="flex">
            <div class="follow-user-info">
              <p class="txt-xxs m-0"><%= user.gender %></p>
              <p class="txt-xxs m-0"><%= user_age %>歳</p>
            </div>
            <% if user.introduction %>
              <p class="pl-3 pr-3 pt-2"><%= (user.introduction).truncate(45) %></p>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/_profile.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="flex col-lg-5">
      <div>
        <% if @user.user_image? %>
          <%= image_tag(@user.user_image.url, class: "profile-image") %>
        <% else %>
          <%= image_tag("user_default.png", class: "profile-image") %>
        <% end %>
      </div>
      <div class="user-detail mt-3 ml-3">
        <p class="txt-m"><b><%= @user.name %></b></p>
        <p>年齢：<%= user_age %> 歳</p>
        <p>性別：<%= @user.gender %></p>
        <div id="follow_buttons_<%= @user.id %>"><%= render "relationships/follow_button", user: @user %></div>
      </div>
    </div>
    <div class="introduction col-lg-7 mt-4">
      <p><b>自己紹介：</b></p>
      <% if @user.introduction? %>
        <p><%= simple_format(@user.introduction) %></p>
      <% else %>
        <p>自己紹介はまだ書かれていません。</p>
      <% end %>
    </div>
  </div>
</div>
<div class="user-page-bar mt-5 mb-3">
  <div class="container">
    <ul class="user-page-bar-lists">
    <% if current_user == @user %>
      <li class="user-page-bar-list"><%= link_to "タイムライン", user_path(@user), class: " #{'page-active' if current_page?(user_path(@user))}" %></li>
      <li class="user-page-bar-list"><%= link_to "お気に入り", favorites_user_path(@user), class: " #{'page-active' if current_page?(favorites_user_path(@user))}" %></li>
      <li class="user-page-bar-list"><%= link_to "下書き", draft_user_path(current_user), class: " #{'page-active' if current_page?(draft_user_path(current_user))}" %></li>
    <% else %>
      <li class="user-page-bar-list"><%= link_to "投稿一覧", user_path(@user), class: " #{'page-active' if current_page?(user_path(@user))}" %></li>
      <li class="user-page-bar-list"><%= link_to "お気に入り", favorites_user_path(@user), class: " #{'page-active' if current_page?(favorites_user_path(@user))}" %></li>
    <% end %>
      <li class="user-page-bar-list"><%= link_to "本棚", bookcases_user_path(@user), class: " #{'page-active' if current_page?(bookcases_user_path(@user))}" %></li>
      <li class="user-page-bar-list"><%= link_to "フォロー中 (#{@user.followings.count})", followings_user_path(@user), class: " #{'page-active' if current_page?(followings_user_path(@user))}" %></li>
      <li class="user-page-bar-list"><%= link_to "フォロワー (#{@user.followers.count})", followers_user_path(@user), class: " #{'page-active' if current_page?(followers_user_path(@user))}" %></li>
    </ul>
  </div>
</div>

app/views/users/bookcases.html.erb
<%= render "profile" %>
<% if @bookcases.present? %>
  <div class="container mt-5 mb-5">
    <%= render "partial/book_list", books: @bookcases %>
    <%= paginate @bookcases %>
  </div>
<% else %>
  <div class="container text-center mt-5 mb-5">
    <p>本棚にはまだ本がありません。</p>
  </div>
<% end %>

app/views/users/draft.html.erb
<%= render "profile" %>
<% if @draft_reviews.exists? %>
  <div class="container mb-5">
    <div class="book_review_boxs">
      <% @draft_reviews.each do |review| %>
        <%= render "partial/book_review", review: review %>
      <% end %>
      <%= paginate @draft_reviews %>
    </div>
  </div>
<% else %>
  <div class="text-center mt-5 mb-5">
    <p>下書きはまだありません。</p>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="text-center">
  <p class="txt-xl headline mb-5 mt-5">アカウント設定</p>
</div> 
<div class="row mb-5">                                               
  <div class="offset-sm-2 col-sm-8">
    <%= form_with(model: @user, local:true) do |f| %>
    <%= render 'partial/error_messages', model: f.object %>
      <div class="form-item flex">
        <%= f.label :name, "名前", class: "form-label" %>
        <%= f.text_field :name, class: "form-input" %>
      </div>
      <div class="form-item flex">
        <div class="form-label">
          <p class="gender">性別</p>
        </div>
        <div class="form-input">
          <%= f.label :gender, "男性" %>
          <%= f.radio_button :gender, "男性", class: "mr-2" %>
          <%= f.label :gender, "女性" %>
          <%= f.radio_button :gender, "女性", class: "mr-2" %>
        </div>
      </div>
      <div class="form-item flex">
        <%= f.label :user_image, "プロフィール画像", class: "form-label" %>
        <%= f.file_field :user_image, class: "form-input" %>
      </div>
      <div class="form-item flex">
        <%= f.label :birthday, "生年月日", class: "form-label" %>
        <div class="form-input">
          <%= f.date_select :birthday, {use_month_numbers: true, start_year: 1930, end_year: (Time.now.year - 10), default: Date.new(1989, 1, 1), date_separator: "／"} %>
        </div>
      </div>
      <div class="form-item flex">
        <%= f.label :introduction, "自己紹介", class: "form-label-introduction" %>
        <%= f.text_area :introduction, class: "form-input-introduction" ,rows: 3 %>
      </div>
      <div class="text-center mt-5">
        <%= f.submit '更新する', class: 'new-btn submit-btn' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/favorites.html.erb
<%= render "profile" %>
<% if @favorites.exists? %>
  <div class="container mb-5">
    <div class="book_review_boxs">
      <% @favorites.each do |review| %>
        <%= render "partial/book_review", review: review %>
      <% end %>
    </div>
    <%= paginate @favorites %>
  </div>
<% else %>
  <div class="text-center mt-5 mb-5">
    <p>お気に入りの投稿はまだありません。</p>
  </div>
<% end %>

app/views/users/followers.html.erb
<%= render "profile" %>
<% if @followers.present? %>
  <%= render "follow_user", users: @followers %>
<% else %>
  <div class="container text-center mt-5 mb-5">
    <p>フォロワーはまだいません。</p>
  </div>
<% end %>

app/views/users/followings.html.erb
<%= render "profile" %>
<% if @followings.present? %>
  <%= render "follow_user", users: @followings %>
<% else %>
  <div class="container text-center mt-5 mb-5">
    <p>フォロしているユーザーはまだいません。</p>
  </div>
<% end %>

app/views/users/new.html.erb
<div class="text-center">
  <p class="txt-xl headline mb-5 mt-5">会員登録</p>
</div>

<div class="row mb-5">                                                                           
  <div class="offset-sm-2 col-sm-8">
    <%= form_with(model: @user, local:true) do |f| %>
    <%= render 'partial/error_messages', model: f.object %>
      <div class="form-item flex">
        <%= f.label :name, "名前", class: "form-label" %>
        <%= f.text_field :name, class: "form-input" %>
      </div>
      <div class="form-item flex">
        <%= f.label :email, "メールアドレス", class: "form-label" %>
        <%= f.email_field :email, class: "form-input" %>
      </div>
      <div class="form-item flex">
        <%= f.label :password, "パスワード", class: "form-label" %>
        <%= f.password_field :password, class: "form-input" %>
      </div>
      <div class="form-item flex">
        <%= f.label :password_confirmation, "パスワード（確認用）", class: "form-label" %>
        <%= f.password_field :password_confirmation, class: "form-input" %>
      </div>
      <div class="text-center mt-5">
        <%= f.submit '新規登録', class: 'new-btn submit-btn' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<%= render "profile" %>
<% if @reviews.exists? %>
  <div class="container mb-5">
    <div class="book_review_boxs">
      <% @reviews.each do |review| %>
        <%= render "partial/book_review", review: review %>
      <% end %>
    </div>
    <%= paginate @reviews %>
  </div>
<% else %>
  <div class="text-center mt-5 mb-5">
    <p>投稿はまだありません。</p>
  </div>
<% end %>