config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'toppages#index'

  get "signup", to: "users#new"
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  post 'guest_login', to: "guest_sessions#create"

  resources :users, only: %i[show create edit update] do
    member do
      get :followings
      get :followers
      get :favorites
      get :bookcases
      get :draft
    end
  end
  resources :favorites, only: %i[create destroy]
  resources :relationships, only: %i[create destroy]
  resources :bookcases, only: %i[create destroy]

  get 'books/search', to: "books#search"
  resources :books, only: %i[show] do
    resources :reviews, only: %i[show create update destroy] do
      resources :comments, only: %i[create update edit destroy]
    end
    collection do
      get "reviews", to: "reviews#index"
    end
  end

  resources :notifications, only: %i[index]
end

app/views/partial/_book_list.html.erb
<div class="books_list">
  <% if books %>
    <% books.each do |book| %>
      <div class="partial_book">
        <%= link_to image_tag(book.image_url, class:"book-image"), book_path(book.isbn) %>
        <p><%= book.title %></p>
      </div>
    <% end %>
  <% end %>
</div>

app/views/partial/_book_review.html.erb
<div class="book-review-box">
  <div class="review-content">
    <%= link_to book_review_path(review.book, review) do %>
      <div class="flex mb-3">
        <div> 
          <% if review.user.user_image? %>
            <%= image_tag(review.user.user_image.url, class: "user-image") %>
          <% else %>
            <%= image_tag("user_default.png", class: "user-image") %>
          <% end %>
        </div>
        <p class="thin-font pt-2 pl-2"><%= review.user.name %></p>
      </div>
      <div class="review-content-detail flex">
        <div class="review-content-image">
          <%= image_tag(review.book.image_url, class: "book-image") %>
        </div>
        <div class="pl-3">
          <p class="mb-1"><%= review.book.title %></p>
          <p class="thin-font txt-xxs txt-author"><%= review.book.author %></p>
          <%= simple_format(strip_tags(review.content).truncate(80), class:"sentence-font margin-0") %>
        </div>
      </div>
    <% end %>
  </div>
  <div class="review-sub mt-2">
    <div class="flex">
      <div class="favo-comment favorite_buttons_<%= review.id %>"><%= render "favorites/favorite_button", review: review %></div>
      <div class="favo-comment pl-1"><i class="far fa-comment fa-lg"></i><small class="subscript"><%= review.comments.count %></small></div>
    </div>
    <small class="text-muted"><%= time_ago_in_words(review.updated_at).upcase %>前</small>
  </div>
</div>

app/views/partial/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/partial/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <% if message_type == "success" %>
    <div class="f-message alert alert-<%= message_type %>">
      <i class="far fa-check-circle fa-lg"></i> <%= message %>
      <button type="button" class="close pl-1" data-dismiss="alert">&times;</button>
    </div>
  <% end %>
  <% if message_type == "danger" %>
    <div class="f-message alert alert-<%= message_type %>">
      <i class="fas fa-exclamation-circle"></i></i> <%= message %>
      <button type="button" class="close pl-1" data-dismiss="alert">&times;</button>
    </div>
  <% end %>
<% end %>

app/views/partial/_footer.html.erb
<footer>
  <div class="text-center">
    <small>©︎2021 Share-read All Rights Reserved.</small>
  </div>
</footer>

app/views/partial/_header.html.erb
<header>
  <nav class="navbar navbar-expand-sm navbar-light">
    <div class="container flex">
      <div class="navbar-left flex">
        <%= link_to (image_tag "top_logo", class: "top_logo mr-2"), root_path %>
        <%= link_to "Share-read", root_path, class: "mr-4 site-title md-none" %>
        <%= form_tag(books_search_path, method: :get, class: 'flex search-form') do %>
          <%= text_field_tag :title, @title, class: 'form-control search-bar', placeholder: '本のタイトル' %>
          <%= button_tag type: "submit",class: "btn search-btn" do %>
            <i class="fas fa-search"></i>
          <% end %>
        <% end %>
      </div>
      <div class="navbar-right">
        <ul class="flex navbar-right-items">
          <% if logged_in? %>
            <li class="nav-item">
              <%= link_to notifications_url, class: "nav-link" do %>
                <% if unchecked_notifications.any? %>
                    <i class="fas fa-bell fa-lg"></i><i class="fas fa-circle circle-shape"></i>
                <% else %>
                    <i class="fas fa-bell fa-lg"></i>
                <% end %>
              <% end %>
            </li>
            <li class="nav-item dropdown">
              <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"><i class="fas fa-user fa-lg"></i></a>
              <ul class="dropdown-menu dropdown-menu-right">
                <li class="dropdown-item"><%= link_to "マイページ", user_path(current_user) %></li>
                <li class="dropdown-divider"></li>
                <li class="dropdown-item"><%= link_to "アカウント設定", edit_user_path(current_user) %></li>
                <li class="dropdown-divider"></li>
                <li class="dropdown-item"><%= link_to "ログアウト", logout_path, method: :delete %></li>
              </ul>
            </li>
          <% else %>
              <li class="nav-item">
                <%= link_to signup_path, class: "btn nav-btn register-btn txt-xxs" do %>
                  <i class="fas fa-user-plus"></i> <span class="sm-none">会員登録</span>
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to login_path, class: "btn nav-btn login-btn txt-xxs" do %>
                  <i class="fas fa-sign-in-alt"></i> <span class="sm-none">ログイン</span>
                <% end %>
              </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>