config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'toppages#index'

  get "signup", to: "users#new"
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  post 'guest_login', to: "guest_sessions#create"

  resources :users, only: %i[show create edit update] do
    member do
      get :followings
      get :followers
      get :favorites
      get :bookcases
      get :draft
    end
  end
  resources :favorites, only: %i[create destroy]
  resources :relationships, only: %i[create destroy]
  resources :bookcases, only: %i[create destroy]

  get 'books/search', to: "books#search"
  resources :books, only: %i[show] do
    resources :reviews, only: %i[show create update destroy] do
      resources :comments, only: %i[create update edit destroy]
    end
    collection do
      get "reviews", to: "reviews#index"
    end
  end

  resources :notifications, only: %i[index]
end

app/controllers/toppages_controller.rb
# frozen_string_literal: true

class ToppagesController < ApplicationController
  def index
    @reviews = Review.where(status: 1).includes(:book, :user).order(updated_at: :desc)
  end
end

app/helpers/toppages_helper.rb
# frozen_string_literal: true

module ToppagesHelper
end

app/views/toppages/index.html.erb
<% if logged_in? %>
  <div class="topwrapper">
    <p class="txt-xl topwrapper-login-message md-none">shareして本の知識を自分のものに</p>
    <div class="flex topwrapper-logo">
      <%= image_tag("top_logo", class: "top_logo-l") %>
      <p class="site-title-l sm-none pl-3">Share-read</p>
    </div>
  </div>
  <div class="container review-list mb-5">
    <div class="text-center">
      <div class="headline mt-5 mb-5">
        <p class="txt-l margin-0"> 最近のレビュー</p>
      </div>
      <div class="all-review-btn mt-5">
        <%= link_to reviews_books_path do %>
          <p class="margin-0"><span class="md-none">全てのレビュー</span><i class="fas fa-chevron-right"></i></p>
        <% end %>
      </div>
    </div>
    <div class="book_review_boxs">
      <% @reviews.first(4).each do |review| %>
        <%= render "partial/book_review", review: review %>
      <% end %>
    </div>
  </div>
<% else %>
  <div class="topwrapper">
    <div class="concept-message">
      <p class="concept-message-detail md-none txt-m mb-2">本を読んでそのままになっていませんか？</p>
      <p class="concept-message-detail md-none txt-m">本の内容をshareして知識を自分のものにしましょう</p>
    </div>
    <div class="flex topwrapper-logo">
      <%= image_tag("top_logo", class: "top_logo-l") %>
      <p class="site-title-l sm-none pl-3">Share-read</p>
    </div>
  </div>
  <div class="container review-list mb-5">
    <div class="text-center">
      <div class="headline mt-5 mb-5">
        <p class="txt-l m-0"> 最近のレビュー</p>
      </div>
    </div>
    <div class="book_review_boxs">
      <% @reviews.first(4).each do |review| %>
        <%= render "partial/book_review", review: review %>
      <% end %>
    </div>
  </div>
<% end %>